
backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "games"
    label: "Games"
    folder: "content/games"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Rating", name: "rating", widget: "number", value_type: "float" }
